title: Productos
sections:
  cover:
    type: fields
    fields:
      bg:
        type: files
        max: 1
        label: Imagen de portada
  pages:
    headline: Páginas
    templates:
      - product

    

